<a href="https://colab.research.google.com/github/topguns837/Tensorflow-deeplearning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''
Topics to be covered :
->Intro to tensors
-> getting info from tensors
->tensor manipulation
->tensors and numpy
->@tf.function
->using GPU/TPU with tensorflow
->exercises
'''

'\nTopics to be covered :\n->Intro to tensors\n-> getting info from tensors\n->tensor manipulation\n->tensors and numpy\n->@tf.function\n->using GPU/TPU with tensorflow\n->exercises\n'

## Introduction to Tensors

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.7.0


In [ ]:
#Create tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#Check the no of dimensions of a tensor
scalar.ndim

0

In [ ]:
#Create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#Create a matrix
matrix=tf.constant([[10,7],
                   [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#Create another matrix
another_matrix=tf.constant([[10.,7.],
                            [3.,2.],
                            [8.,9.]],dtype=tf.float16)

In [ ]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#Create a tensor
tensor=tf.constant([[[1,2,3],
                    [4,5,6]],
                    [[7,8,9],
                     [10,11,12]],
                    [[13,14,15],
                     [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

### Creating tensors with tf.variable()

In [ ]:
#Creare the same tensor as above using tf.variable()
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#Lets's try change one of the elements in changeable_tensor
#changeable_tensor[0] = 7
#changeable_tensor

In [ ]:
#Trying .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
#Changing unchangeable tensor
#unchangeable_tensor[0].assign(7)
#unchangeable_tensor

### Creating random tensors

In [ ]:
#Random tensors are tensors with random size and nos
#We initialze the weights using random tensors and then change their values
#accordingly using backpropagation



In [ ]:
random_1 = tf.random.Generator.from_seed(7)  #set seed for reproducibility
random_1 = random_1.normal(shape=(3,3))
random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3,3))
random_1==random_2 
  

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])>

### Shuffle the order of elements in a tensor

In [ ]:
# Shuffle a tensor --> used for shuffling datasets
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled.ndim

2

In [ ]:
#shuffle out not shuffled tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Checkout https://www.tensorflow.org/api_docs/python/tf/random/set_seed for more info on random_seeds

In [ ]:
tf.random.set_seed(42)
print(tf.random.shuffle(not_shuffled,seed=42))
print(tf.random.shuffle(not_shuffled,seed=42))

tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  5]
 [10  7]
 [ 3  4]], shape=(3, 2), dtype=int32)


In [ ]:
print(tf.random.shuffle(not_shuffled,seed=41))
print(tf.random.shuffle(not_shuffled,seed=41))

tf.Tensor(
[[ 3  4]
 [ 2  5]
 [10  7]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32)


### Other ways to make tensors

In [ ]:
 #Create a tensor of all ones
 tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
#Numpy arrays can also be converted to tensorflow tensors
#Main difference b/w Numpy arrays and Tensorflow tensors is that tensorflow tensors 
#can be run on a GPU for faster computing

In [ ]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32) 
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A,shape = (2,3,4))
B = tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
A.ndim,B.ndim

(3, 1)


### Getting info from tensors

### --> Shape
### --> Rank
### --> Axis/Dimension
### --> Size

In [ ]:
# Create a rank 4 tensor
# No of dimensions = 4
rank_4_tensor = tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0][0][0]

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

In [ ]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of our tensor
print("Datatype of every element : ",rank_4_tensor.dtype)
print("No of dimensions(rank) : ",rank_4_tensor.ndim)
print("Shape of tensor : ",rank_4_tensor.shape)
print("Element along 0 axis : ",rank_4_tensor.shape[0])
print("Elements along last axis : ",rank_4_tensor.shape[-1])
print("Total no of elements in our tensor : ",tf.size(rank_4_tensor).numpy()) 

Datatype of every element :  <dtype: 'float32'>
No of dimensions(rank) :  4
Shape of tensor :  (2, 3, 4, 5)
Element along 0 axis :  2
Elements along last axis :  5
Total no of elements in our tensor :  120


### Indexing tensors : Just like Python lists

In [ ]:
## Get the first 2 elements of each dimension

rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension except the last one

rank_4_tensor[:1,:1,:1] #rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#Create a rank 2 tensor
rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor.shape , rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
#Get the last item of each of our rank 2 tensor
rank_2_tensor[:,-1:]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[7],
       [4]], dtype=int32)>

In [ ]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[:,:,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
#Alternative to tf.newaxis
new_tensor = tf.expand_dims(rank_2_tensor , axis = -1) #expand the final axis
new_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
#Expand zero axis
tf.expand_dims(rank_2_tensor , axis = 0) #expand the 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating tensors

** Basic operations**

In [ ]:
# Tensor addition
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
#Original tensor is still unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
#Changing original tensor
tensor+=10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
#Multiplication also works
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]], dtype=int32)>

In [ ]:
#Subtraction of tensors
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# We can use the tensorflow built-in function too...
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]], dtype=int32)>

** Matrix Multiplication **

In [ ]:
# Matrix multiplication is one of the most common operations in ML
# Using tensorflow
tf.matmul(tensor,tensor)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [ ]:
# Using Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [ ]:
tensor.shape

TensorShape([2, 2])

In [ ]:
# Creating a (3,2) tensor
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

#Another (2,3) tensor
Y = tf.constant([[2,2,2],
                 [3,5,7]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[2, 2, 2],
        [3, 5, 7]], dtype=int32)>)

In [ ]:
tf.matmul(X,Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 8, 12, 16],
       [18, 26, 34],
       [28, 40, 52]], dtype=int32)>

In [ ]:
#Try matrix multiplication with transpose
tf.matmul(tf.transpose(X),X)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[35, 44],
       [44, 56]], dtype=int32)>

In [ ]:
# We will be dealing with a lot of matrix multiplication while using nerural networks

In [ ]:
### Dot Product using tf.tensordot() and tf.matmul()

In [ ]:
tf.tensordot(tf.transpose(X),Y,axes=0)

<tf.Tensor: shape=(2, 3, 2, 3), dtype=int32, numpy=
array([[[[ 2,  2,  2],
         [ 3,  5,  7]],

        [[ 6,  6,  6],
         [ 9, 15, 21]],

        [[10, 10, 10],
         [15, 25, 35]]],


       [[[ 4,  4,  4],
         [ 6, 10, 14]],

        [[ 8,  8,  8],
         [12, 20, 28]],

        [[12, 12, 12],
         [18, 30, 42]]]], dtype=int32)>

In [ ]:
# Check the values of Y , reshape Y and transposed Y
print("Normal Y : ",Y,"\n")
print(Y,"\n")
print("Y reshaped to (3,2) :")
print(tf.reshape(Y,(3,2)),"\n")
print("Y transposed : ")
print(tf.transpose(Y))

Normal Y :  tf.Tensor(
[[2 2 2]
 [3 5 7]], shape=(2, 3), dtype=int32) 

tf.Tensor(
[[2 2 2]
 [3 5 7]], shape=(2, 3), dtype=int32) 

Y reshaped to (3,2) :
tf.Tensor(
[[2 2]
 [2 3]
 [5 7]], shape=(3, 2), dtype=int32) 

Y transposed : 
tf.Tensor(
[[2 3]
 [2 5]
 [2 7]], shape=(3, 2), dtype=int32)


### Changing the datatype of a tensor


In [ ]:
# Create a new tensor with default datatype
B = tf.constant([1.7,4.2])
B


<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 4.2], dtype=float32)>

In [ ]:
C = tf.constant([1,10])
C

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 1, 10], dtype=int32)>

In [ ]:
tf.__version__

'2.7.0'

In [ ]:
# Change from float32 to float16
D = tf.cast(B,dtype = tf.float16)
D , B

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 4.2], dtype=float16)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 4.2], dtype=float32)>)

In [ ]:
# Change from int32 to float32
E = tf.cast(C , dtype = tf.float32)
E , C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 1., 10.], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 1, 10], dtype=int32)>)

In [ ]:
E_float16 = tf.cast(E , dtype = tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 1., 10.], dtype=float16)>

### Aggregating Tensors

In [ ]:
# Aggregating tensors = Condesing them from multiple values down to a smaller amount of values

In [ ]:
# Get the absolute values
D = tf.constant([-7 , -10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

# Lets go through the following forms of aggregation
* Get the min of a tensor
* Get the max of a tensor
* Get the mean of a tensor
* Get the sum of a tensor


In [ ]:
#Create a random tensor with values b/w 0 and 100 of size 50
import numpy as np
E = tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([64, 88, 90, 35, 51, 41, 86, 82, 33,  6,  5, 62, 73, 61, 43, 30, 33,
       94, 87, 54, 82, 89, 64,  0, 90, 53, 29, 60, 20, 97, 63, 93, 59, 39,
       33, 35, 92, 88, 94, 47, 36, 57, 38, 59, 32, 57, 67, 92, 36, 62])>

In [ ]:
tf.size(E) , E.shape , E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
#Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [ ]:
#Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=57>

In [ ]:
# Find the sum 
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2881>

In [ ]:
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([64, 88, 90, 35, 51, 41, 86, 82, 33,  6,  5, 62, 73, 61, 43, 30, 33,
       94, 87, 54, 82, 89, 64,  0, 90, 53, 29, 60, 20, 97, 63, 93, 59, 39,
       33, 35, 92, 88, 94, 47, 36, 57, 38, 59, 32, 57, 67, 92, 36, 62])>

In [ ]:
#Find the variance and standard deviation of the above tensor
import math
squared_sum = 0
for i in E :
  squared_sum += i**2
print("Variance : ",int(squared_sum/50 - int(tf.reduce_mean(E))) )
print("Standard Deviation :",math.sqrt(int(squared_sum/50 - int(tf.reduce_mean(E)))))


Variance :  3936
Standard Deviation : 62.73754856543249


In [ ]:
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([64, 88, 90, 35, 51, 41, 86, 82, 33,  6,  5, 62, 73, 61, 43, 30, 33,
       94, 87, 54, 82, 89, 64,  0, 90, 53, 29, 60, 20, 97, 63, 93, 59, 39,
       33, 35, 92, 88, 94, 47, 36, 57, 38, 59, 32, 57, 67, 92, 36, 62])>

In [ ]:
#print("Variance : ",int(tf.math.reduce_std(E))**2)
#print("Standard Deviation : ",tf.maths.reduce_std(E))


In [ ]:
#Using tensorflow methods
import tensorflow_probability as tfp
print("Variance : ",tfp.stats.variance(E))

#tf.math.reduce_std needs input tensor's dtype as float32
print("Standard Deviation : ",tf.math.reduce_std(tf.cast(E,dtype=tf.float32)))

Variance :  tf.Tensor(674, shape=(), dtype=int64)
Standard Deviation :  tf.Tensor(25.957575, shape=(), dtype=float32)


### Find the positional maximum and minimum 

In [ ]:
#Create a new tensor for finding positional min and max
tf.random.set_seed(42)
F = tf.random.uniform(shape = [50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#Find the positional max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
#Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#Find the positional minimum
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor

In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G


<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G) # Removes dimensions of size 1 from shape of the tensor
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

### One hot Encoding

In [ ]:
# Creare a list if indices
some_list = [0,1,2,3] #could be red,green,blue,purple

#One hot encoding
tf.one_hot(some_list,depth = 5)

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot encoding
tf.one_hot(some_list , depth=4 ,on_value = "yo I love deep learning",off_value="I like music")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep learning', b'I like music', b'I like music',
        b'I like music'],
       [b'I like music', b'yo I love deep learning', b'I like music',
        b'I like music'],
       [b'I like music', b'I like music', b'yo I love deep learning',
        b'I like music'],
       [b'I like music', b'I like music', b'I like music',
        b'yo I love deep learning']], dtype=object)>

### Square , Log , Square root

In [ ]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
# Log
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensor and Numpy

In [ ]:
# Create a tensor directly from a numpy array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Convert tensor back to numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
type(J.numpy())

numpy.ndarray

In [ ]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [ ]:
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])

#Check the datatypes
numpy_J.dtype , tensor_J.dtype

(tf.float64, tf.float32)